version: '3'

services:
  memcached:
    image: memcached:latest
    container_name: memcached-container
    ports:
      - "11211:11211"
    restart: always

  memcached-exporter:
    image: prom/memcached-exporter
    container_name: memcached-exporter-container
    ports:
      - "9150:9150"
    restart: always
    command:
      - "--memcached.address=memcached:11211"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus-container
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - --config.file=/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    container_name: grafana-container
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - prometheus

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    environment:
      - discovery.type=single-node
    volumes:
      - elk-storage:/var/lib/grafana

  logstash:
    image: docker.elastic.co/logstash/logstash:7.15.0
    depends_on:
      - elasticsearch
    volumes:
      - ./logstash/config:/usr/share/logstash/config
      - ./logstash/pipeline:/usr/share/logstash/pipeline

  kibana:
    image: docker.elastic.co/kibana/kibana:7.15.0
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"

  django-app:
    build:
      context: ../ost
      dockerfile: Dockerfile.django
    container_name: django-app-container
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
    volumes:
      - ../ost:/app

volumes:
  grafana-storage:
  elk-storage: