# Generated by Django 4.2 on 2023-12-08 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_hotel_hotels_hote_airport_5ff767_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='hotel',
            name='hotels_hote_airport_5ff767_idx',
        ),
        migrations.AddIndex(
            model_name='hotel',
            index=models.Index(fields=['airport_distance', 'train_station_distance', 'bus_station_distance'], name='infra_idx'),
        ),
    ]
